# SPDX-FileCopyrightText: 2023 Adam Wojdyła <adam.wojdyla@outlook.com>
#
# SPDX-License-Identifier: MIT

description: "ResNet34-TransferLearning"
name: "resnet34"
target:
  _target_: torchvision.models.resnet34
  weights: IMAGENET1K_V1