# SPDX-FileCopyrightText: 2023 Adam Wojdyła <adam.wojdyla@outlook.com>
#
# SPDX-License-Identifier: MIT

description: "VGG16-TransferLearning"
name: "vgg16"
target:
  _target_: torchvision.models.vgg16
  weights: IMAGENET1K_V1